apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
  architecture: null
controlPlane:
  architecture: null
  hyperthreading: Enabled
  name: master
  replicas: 3
fips: false
metadata:
  name: sno-lab
  namespace: cluster0
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  - cidr: fd01::/48
    hostPrefix: 64
  machineNetwork:
  - cidr: 192.168.110.0/24
  - cidr: fd00:110::/64
  serviceNetwork:
  - 172.30.0.0/16
  - fd02::/112
  networkType: OVNKubernetes
platform:
  baremetal:
    apiVIPs:
    - 192.168.110.10
    - fd00:110::10
    ingressVIPs:
    - 192.168.110.11
    - fd00:110::11
pullSecret: "{\n  \"auths\": {\n    \"cloud.openshift.com\": {\n      \"auth\": \"\
  b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZWIyZDVkZmUxYWM0NDJlMzgwYzAwMDcxYjYzNzExYmI6RlJKSFFORUNFRVpaQVY1NzhJR1NIWEFIUDY3TEMxSVNZTjhUWllGREVITEdPVUwwTEYyVk0xTE1PNUNWMDJKMg==\"\
  ,\n      \"email\": \"fpaoline@redhat.com\"\n    },\n    \"quay.io\": {\n      \"\
  auth\": \"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZWIyZDVkZmUxYWM0NDJlMzgwYzAwMDcxYjYzNzExYmI6RlJKSFFORUNFRVpaQVY1NzhJR1NIWEFIUDY3TEMxSVNZTjhUWllGREVITEdPVUwwTEYyVk0xTE1PNUNWMDJKMg==\"\
  ,\n      \"email\": \"fpaoline@redhat.com\"\n    },\n    \"registry.connect.redhat.com\"\
  : {\n      \"auth\": \"fHVoYy1wb29sLWU2YzVkNjM5LTM0NWEtNDcyNC04MGNiLWE1ZWE2YjliZGMzMjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlNelJpTlRrek9XSmpaVGswTTJRME9HVTJNamM1TURZNU1qWTJZek5qTlNKOS5IT1ROZ3Nmb056YWp2R0NESmtVeHNWSFRhTnBaSlRTRzEyeXJYcVBFSzJrSE9ZeHlGV0RsUWUwcVFCWDI2N1FTWkhIdzU2V1lDMko2cW9HTGtRbUpnV1pkMGd6U2xoTTRaUl9iY2t2bERPV0F5aDUzQU1JVHVVa1lGbmdqSi1mSFNHQVJMRk9MYzAtVEktUHUxcDBxblRpUkZtS2tqbzR5ejg4bjJpNkVIWU5zTUpOb3JhMW1VM0ZsdWRKNmUxdFJFWXRydEM4bUNWMkEtNjBRLUlkNTd4UTdaVmltdVRWMEVCak5tRmQ0eEtrbTUyejhtWkxwTlB3c2QwTTk2Z0l3N2t6c3c2MXVlb18xc1lIZE81eEhZQTY1TTkyeUx1OW1PQV9MN1VCdFBOaVRJWDhKQ1F3MmlvbWhLdkdiMldMSU9vM3VKQVgxNmdtRTJRalk3OUtTMUx5MHhudFF4bDFmRFBKbGFzNDEtVlBKRlVwMUlKRnI0ZHVPZF9seGZ1Y0NKSVZTYlBIWFhPVFNpaU9taUJISDNhSWpfcThyNmZlTGNkaHVQZFRrQzg1a3VOckNaeGExMzdaU1dHSmlrQ015bzFWYzdSZkpFejY1X0MzQzR2X0VDMm9mSHMtOE1kMnVVOXNKQ0ZpdXhmQ0NvUFRhdlRObHVaQkV4ZzQ4NzBkNnM3azRiam14Ri1rR2VLNUExekV3a0JTNy1qM0dwVzdmNllxWDNDa1llTWhQWnliYlRsZG5mMkVLTGhaZm1DQUphNmFOb09Zelg2MHprS3RaVGpNcGRLUkMteEN0LTdVQVlDTE03T0FpZ0hnNzVMaDd3emlWTlFjNlFmekZjWVVKeWE0YTVpd0hiMHB3S3RGa3dsSlZMeUd3c1R5ejJGVmtoMV85ZWFBWnFrRQ==\"\
  ,\n      \"email\": \"fpaoline@redhat.com\"\n    },\n    \"registry.redhat.io\"\
  : {\n      \"auth\": \"fHVoYy1wb29sLWU2YzVkNjM5LTM0NWEtNDcyNC04MGNiLWE1ZWE2YjliZGMzMjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlNelJpTlRrek9XSmpaVGswTTJRME9HVTJNamM1TURZNU1qWTJZek5qTlNKOS5IT1ROZ3Nmb056YWp2R0NESmtVeHNWSFRhTnBaSlRTRzEyeXJYcVBFSzJrSE9ZeHlGV0RsUWUwcVFCWDI2N1FTWkhIdzU2V1lDMko2cW9HTGtRbUpnV1pkMGd6U2xoTTRaUl9iY2t2bERPV0F5aDUzQU1JVHVVa1lGbmdqSi1mSFNHQVJMRk9MYzAtVEktUHUxcDBxblRpUkZtS2tqbzR5ejg4bjJpNkVIWU5zTUpOb3JhMW1VM0ZsdWRKNmUxdFJFWXRydEM4bUNWMkEtNjBRLUlkNTd4UTdaVmltdVRWMEVCak5tRmQ0eEtrbTUyejhtWkxwTlB3c2QwTTk2Z0l3N2t6c3c2MXVlb18xc1lIZE81eEhZQTY1TTkyeUx1OW1PQV9MN1VCdFBOaVRJWDhKQ1F3MmlvbWhLdkdiMldMSU9vM3VKQVgxNmdtRTJRalk3OUtTMUx5MHhudFF4bDFmRFBKbGFzNDEtVlBKRlVwMUlKRnI0ZHVPZF9seGZ1Y0NKSVZTYlBIWFhPVFNpaU9taUJISDNhSWpfcThyNmZlTGNkaHVQZFRrQzg1a3VOckNaeGExMzdaU1dHSmlrQ015bzFWYzdSZkpFejY1X0MzQzR2X0VDMm9mSHMtOE1kMnVVOXNKQ0ZpdXhmQ0NvUFRhdlRObHVaQkV4ZzQ4NzBkNnM3azRiam14Ri1rR2VLNUExekV3a0JTNy1qM0dwVzdmNllxWDNDa1llTWhQWnliYlRsZG5mMkVLTGhaZm1DQUphNmFOb09Zelg2MHprS3RaVGpNcGRLUkMteEN0LTdVQVlDTE03T0FpZ0hnNzVMaDd3emlWTlFjNlFmekZjWVVKeWE0YTVpd0hiMHB3S3RGa3dsSlZMeUd3c1R5ejJGVmtoMV85ZWFBWnFrRQ==\"\
  ,\n      \"email\": \"fpaoline@redhat.com\"\n    },\n    \"registry.ci.openshift.org\"\
  : {\n      \"auth\": \"dXNlcjpzaGEyNTZ+SkF2YWVnQmxMUnk0XzVtT19ZQXZPb1dFR1F5ekZadlpBQW55Nk5XTE0zbw==\"\
  \n    }\n  }\n}"
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjrW9EiG5PG6sGGFnXLjCfjayC4j8lWueZaHCkQzhT9PG8kM4wk1rCFXdDKsxOuoiVxKKbY7D7aeoAoVWpQ4WXm5lqyQbSZA59+3bf2Y6XfKDbuId7QLnDOZUy901xnnTCDBVe6POJ4MmXnSs5hf90477p/a6bq+2UDSnuGRlde3XCZiCTziSqgFz0TKbqxVzKSHyi6Oo5HVqJTIVWyi1x5fSqlRNz2+w6FGQfi0D/hD8Hhc/zsA6f/Sx5tZkgWt9pQkZnmDtwovNfIvI8IXUxxefvPAX9MlrMp4Lsej9bIC9JUgf9epfHJWFU90WoIUfQg5ky1aWzqBLLJb5jYMC9pqj23nBBl+KD7qaXePYHNRhFE3zDe6HjuKrzp+gMyTih4hyKZvP0POdPU282QMfKd4ulBHlaG6c8AoiwfG1dyccLer5n2FFRFYRi1sL+MvvdsdClqWqt2gCprW9JNdJpxZqQM2EEwvtQnbzTq08yqv/Gbb8YgwoaopV5RFPG3f50tCxqMPliExkrqlFJMNtPOSth/Pw4UjTjTyoLNcYKMEhuhT8AKwoSclaGotRLA18X3fRznxYnUyjxkL28GBtOagGYHEPR+Cb3QP7N1eMmFYSeWEK8cNcbMPjjXndRY9lUzUnrq76upyvYO+I3ChLMzEE/Ark8j3QeAomICl0zw==
  fpaoline@cnfdr7.telco5g.eng.rdu2.redhat.com
